import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

class EmailAgent:
    """
    Agent 3: Analysis report को email करता है
    """
    
    def __init__(self):
        self.sender = os.getenv("EMAIL_SENDER")
        self.password = os.getenv("EMAIL_PASSWORD")
        self.recipient = os.getenv("RECIPIENT_EMAIL")
        self.smtp_server = "smtp.gmail.com"  # Gmail के लिए
        self.smtp_port = 587
        
    def send_report(self, analysis: str, summary: dict = None) -> bool:
        """
        Analysis report भेजो (HTML format में, professional look)
        """
        
        today = datetime.now().strftime("%B %d, %Y")
        
        # HTML Email Template
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
                .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                           color: white; padding: 20px; text-align: center; }}
                .content {{ padding: 20px; background: #f8f9fa; }}
                .footer {{ text-align: center; font-size: 12px; color: #666; margin-top: 20px; }}
                h2 {{ color: #667eea; }}
                hr {{ border: none; border-top: 1px solid #ddd; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>📊 Daily Report Analysis</h1>
                    <p>{today}</p>
                </div>
                <div class="content">
                    {self._markdown_to_html(analysis)}
                </div>
                <div class="footer">
                    <p>🤖 Generated by AI Report Agent | Learning from your feedback daily</p>
                    <p><small>Reply to this email with corrections to help me learn!</small></p>
                </div>
            </div>
        </body>
        </html>
        """
        
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"📈 Daily Report - {today}"
        msg['From'] = self.sender
        msg['To'] = self.recipient
        
        msg.attach(MIMEText(html_content, 'html'))
        
        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)
            
            print(f"✅ Email sent to {self.recipient}")
            return True
            
        except Exception as e:
            print(f"❌ Email failed: {e}")
            return False
    
    def _markdown_to_html(self, markdown_text: str) -> str:
        """Simple markdown to HTML converter"""
        # Replace markdown headers
        html = markdown_text.replace('###', '</h3><h3>').replace('##', '</h2><h2>').replace('#', '</h1><h1>')
        html = html.replace('\n', '<br>')
        html = f"<h2>{html}</h2>" if not html.startswith('<') else html
        return html
